### ISSUE TITLE
build envoy with bazel on mips64 

### ISSUE THREAD

**Issue by orangeji11** [packyzbq/bazel-project#1]
你好，我在https://github.com/bazelbuild/rules_go/issues/2611看到了您对该问题的描述，
同样的我在使用bazel构建mips架构上的envoy：bazel build   //source/exe:envoy-static。

在拉取的过程中我发现在拉取x86架构的golang：
Fetching https://dl.google.com/go/go1.13.5.linux-amd64.tar.gz;

而后报错：
ERROR: While resolving toolchains for target @com_envoyproxy_protoc_gen_validate//:protoc-gen-validate: no matching toolchains found for types @io_bazel_rules_go//go:toolchain
ERROR: Analysis of target '//source/exe:envoy-static' failed; build aborted: no matching toolchains found for types @io_bazel_rules_go//go:toolchain

在网上查找后尝试在WORKSPACE中加入：
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
http_archive(
    name = "io_bazel_rules_go",
    sha256 = "207fad3e6689135c5d8713e5a17ba9d1290238f47b9ba545b63d9303406209c6",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/rules_go/releases/download/v0.24.7/rules_go-v0.24.7.tar.gz",
        "https://github.com/bazelbuild/rules_go/releases/download/v0.24.7/rules_go-v0.24.7.tar.gz",
    ],
)
load("@io_bazel_rules_go//go:deps.bzl", "go_register_toolchains", "go_rules_dependencies")
go_rules_dependencies()
go_register_toolchains()

也没有什么效果，
有什么能帮助我的吗谢谢！

**Comment by orangeji11** [comment]
我的bazel版本v2.2.0，envoy-v1.14.4

**Comment by orangeji11** [comment]
@packyzbq 您好

**Comment by packyzbq** [comment]
我当时修改了引用 io_bazel_rules_go 的部分，在调用的一个方法上增加了一个传入的参数，这个参数是指定使用本地的 golang 环境，就解决这个问题了。具体修改如下，不过我编译的是 istio 1.5，可能和您的环境有出入，希望对你有所帮助。
`${source_root}/envoy/bazel/dependency_imports.bzl`**
```diff
- ****go_register_toolchains(go_version)
// 修改使用本地环境的 golang
+ go_register_toolchains(go_version="host")****
```

**Comment by orangeji11** [comment]
@packyzbq 谢谢您的回答。
我按照以下步骤：
1.修改go_register_toolchains(go_version="host")
2.删除.cache/bazel
3.重新执行bazel build //source/exe:envoy-static

它已经不去拉取golang了，但是结果还是之前的报错。
我现在正在查这个问题。

**Comment by orangeji11** [comment]
@packyzbq 您还记得当时构建bazel和envoy的版本号吗

**Comment by orangeji11** [comment]
@packyzbq 您好，
我用--toolchain_resolution_debug打印出
INFO: ToolchainResolution:   Considering toolchain @go_sdk//:go_linux_arm64-impl...
INFO: ToolchainResolution:     Toolchain constraint @platforms//cpu:cpu has value @platforms//cpu:aarch64, which does not match value <missing> from the target platform @local_config_platform//:host
INFO: ToolchainResolution:   Rejected toolchain @go_sdk//:go_linux_arm64-impl, because of target platform mismatch
INFO: ToolchainResolution:   Considering toolchain @go_sdk//:go_linux_mips-impl...
INFO: ToolchainResolution:     Toolchain constraint @platforms//cpu:cpu has value @io_bazel_rules_go//go/toolchain:mips, which does not match value <missing> from the target platform @local_config_platform//:host
INFO: ToolchainResolution:   Rejected toolchain @go_sdk//:go_linux_mips-impl, because of target platform mismatch
INFO: ToolchainResolution:   Considering toolchain @go_sdk//:go_linux_mips64-impl...
INFO: ToolchainResolution:     Toolchain constraint @platforms//cpu:cpu has value @io_bazel_rules_go//go/toolchain:mips64, which does not match value <missing> from the target platform @local_config_platform//:host
INFO: ToolchainResolution:   Rejected toolchain @go_sdk//:go_linux_mips64-impl, because of target platform mismatch
INFO: ToolchainResolution:   Considering toolchain @go_sdk//:go_linux_mips64le-impl...
INFO: ToolchainResolution:     Toolchain constraint @platforms//cpu:cpu has value @io_bazel_rules_go//go/toolchain:mips64le, which does not match value <missing> from the target platform @local_config_platform//:host
INFO: ToolchainResolution:   Rejected toolchain @go_sdk//:go_linux_mips64le-impl, because of target platform mismatch
INFO: ToolchainResolution:   Considering toolchain @go_sdk//:go_linux_mipsle-impl...
INFO: ToolchainResolution:     Toolchain constraint @platforms//cpu:cpu has value @io_bazel_rules_go//go/toolchain:mipsle, which does not match value <missing> from the target platform @local_config_platform//:host
INFO: ToolchainResolution:   Rejected toolchain @go_sdk//:go_linux_mipsle-impl, because of target platform mismatch
上面意思说platform @local_config_platform//:host 没有@io_bazel_rules_go//go/toolchain:mips64 这个值，想问您怎么解决，
这个value应该在那里设置呢？

**Comment by packyzbq** [comment]
我记得当时修改了 io_basel_rules_go 的源码，源码里好像缺少了 mips64le 的映射，具体细节有些忘了。

**Comment by orangeji11** [comment]
@packyzbq 感谢您的回复，在修改编译选项后，我已通过编译。现在关闭问题。

**Comment by zqzzq** [comment]
@packyzbq 大神，请问你有编译好的mips环境istio1.5镜像吗，可不可以共享一下~ 我试着编译了好久都没成功。。

**Comment by packyzbq** [comment]
> @packyzbq 大神，请问你有编译好的mips环境istio1.5镜像吗，可不可以共享一下~ 我试着编译了好久都没成功。。

1.9都出了 为啥还用1.5呢，何况1.5的envoy还有一些bug，而且1.7之后的版本都比1.5的好编译。

**Comment by zqzzq** [comment]
哎，之前在x86上都是用的1.5 ，所以想保持一致，暂时还没有升级新版本的计划
